// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt6nGSagE9njooQm9lWdUmn1ftTPYzztE',
    appId: '1:640904805717:web:e511d7de16126c491543dc',
    messagingSenderId: '640904805717',
    projectId: 'dacs3-7dea8',
    authDomain: 'dacs3-7dea8.firebaseapp.com',
    storageBucket: 'dacs3-7dea8.firebasestorage.app',
    measurementId: 'G-958R1RQ3KQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDebg00b-l82OpdbMCTRDQQ8jn0hVCVpGw',
    appId: '1:640904805717:android:3e6e41379652e4b61543dc',
    messagingSenderId: '640904805717',
    projectId: 'dacs3-7dea8',
    storageBucket: 'dacs3-7dea8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRQVLw4P4VY5BqtCXTWnrQgwZC2jpNwOo',
    appId: '1:640904805717:ios:7a6a15951637eddd1543dc',
    messagingSenderId: '640904805717',
    projectId: 'dacs3-7dea8',
    storageBucket: 'dacs3-7dea8.firebasestorage.app',
    iosBundleId: 'com.example.dacs3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRQVLw4P4VY5BqtCXTWnrQgwZC2jpNwOo',
    appId: '1:640904805717:ios:7a6a15951637eddd1543dc',
    messagingSenderId: '640904805717',
    projectId: 'dacs3-7dea8',
    storageBucket: 'dacs3-7dea8.firebasestorage.app',
    iosBundleId: 'com.example.dacs3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt6nGSagE9njooQm9lWdUmn1ftTPYzztE',
    appId: '1:640904805717:web:987e41b11d41a4901543dc',
    messagingSenderId: '640904805717',
    projectId: 'dacs3-7dea8',
    authDomain: 'dacs3-7dea8.firebaseapp.com',
    storageBucket: 'dacs3-7dea8.firebasestorage.app',
    measurementId: 'G-L97EFPN86T',
  );
}
